"""ServiceSpec -> Dockerfile."""

import json
import shlex

from app_translator.ir import ImageSource
from app_translator.ir import ServiceSpec

STARTUP_PATH = "/usr/local/bin/openhost-start.sh"


def _exec_form(command: str) -> str:
    """Render a command as a JSON exec-form array, using a shell only when it needs one."""
    if any(token in command for token in ("&&", "||", "|", ";", ">", "<", "$(")):
        return json.dumps(["/bin/sh", "-c", command])
    return json.dumps(shlex.split(command))


def render_dockerfile(service: ServiceSpec, *, needs_startup_shim: bool, reset_entrypoint: bool = False) -> str:
    if service.image.kind != "registry":
        raise ValueError("only registry images can be emitted as a generated Dockerfile")

    lines = [
        "# Generated by app-translator.",
        f"FROM {service.image.ref}",
        "",
    ]

    plain = service.plain_env
    if plain:
        lines.append("# Non-secret configuration from the source config.")
        for entry in plain:
            value = entry.value if entry.value is not None else ""
            lines.append(f"ENV {entry.key}={json.dumps(value)}")
        lines.append("")

    if service.http_port is not None:
        # Many images read PORT instead of a fixed listen port; set both.
        lines += [f"ENV PORT={service.http_port}", f"EXPOSE {service.http_port}", ""]

    if needs_startup_shim:
        # The shim replaces the image's own entrypoint, so CMD below must carry the full argv.
        # COPY runs as the base image's user, which may not be able to write to
        # /usr/local/bin, so switch to root for it and invoke through sh rather than
        # relying on the executable bit surviving.
        lines += [
            "USER root",
            f"COPY openhost-start.sh {STARTUP_PATH}",
            f"RUN chmod 0755 {STARTUP_PATH}",
        ]
        if not service.run_as_root and service.image_user:
            lines.append(f"USER {service.image_user}")
        lines.append(f'ENTRYPOINT ["/bin/sh", "{STARTUP_PATH}"]')
    elif service.run_as_root:
        lines.append("USER root")
    elif service.entrypoint:
        lines.append(f"ENTRYPOINT {_exec_form(service.entrypoint)}")
    elif reset_entrypoint:
        # `command` is a full argv, so clear the inherited entrypoint rather than
        # passing the command to it as arguments.
        lines.append("ENTRYPOINT []")

    if service.command:
        lines.append(f"CMD {_exec_form(service.command)}")

    return "\n".join(lines) + "\n"


def describe_image(image: ImageSource) -> str:
    return image.ref
