"""ServiceSpec -> openhost.toml text."""

import json

from app_translator.ir import ServiceSpec

SECRETS_SERVICE_URL = "github.com/imbue-openhost/openhost/services/secrets"
SECRETS_VERSION_SPEC = ">=0.1.0"


def _toml_string(value: str) -> str:
    """TOML basic strings use the same escaping as JSON strings."""
    return json.dumps(value)


def _toml_string_array(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(_toml_string(v) for v in values) + "]"


def render_manifest(service: ServiceSpec, *, version: str = "0.1.0") -> str:
    if service.http_port is None:
        raise ValueError("cannot emit a manifest without a main HTTP port")

    lines: list[str] = [
        "# Generated by app-translator. Edit freely — this is a normal openhost manifest.",
        "",
        "[app]",
        f"name = {_toml_string(service.name)}",
        f"version = {_toml_string(version)}",
    ]
    if service.description:
        lines.append(f"description = {_toml_string(service.description)}")
    dockerfile_path = service.image.ref if service.image.kind == "dockerfile" else "Dockerfile"
    lines += [
        "",
        "[runtime.container]",
        f"image = {_toml_string(dockerfile_path)}",
        f"port = {service.http_port}",
    ]

    for port in service.extra_ports:
        lines += [
            "",
            "[[ports]]",
            f"label = {_toml_string(port.label)}",
            f"container_port = {port.container_port}",
            f"host_port = {port.host_port}",
        ]

    routing: list[str] = []
    if service.health_path:
        routing.append(f"health_check = {_toml_string(service.health_path)}")
    if service.public_paths:
        routing.append(f"public_paths = {_toml_string_array(service.public_paths)}")
    if routing:
        lines += ["", "[routing]", *routing]

    lines += [
        "",
        "[resources]",
        f"memory_mb = {service.resources.memory_mb}",
        f"cpu_cores = {service.resources.cpu_cores}",
    ]
    if service.gpu:
        lines.append("gpu = true  # note: openhost does not currently pass this through to podman")

    data_lines = ["app_data = true"]
    if any(mount.tier == "temp" for mount in service.mounts):
        data_lines.append("app_temp_data = true")
    if any(mount.tier == "archive" for mount in service.mounts):
        data_lines.append("app_archive = true")
    lines += ["", "[data]", *data_lines]

    if service.secret_keys:
        grants = ", ".join("{key = " + _toml_string(key) + "}" for key in service.secret_keys)
        lines += [
            "",
            "[[services.v2.consumes]]",
            f"service = {_toml_string(SECRETS_SERVICE_URL)}",
            'shortname = "secrets"',
            f"version = {_toml_string(SECRETS_VERSION_SPEC)}",
            f"grants = [{grants}]",
        ]

    return "\n".join(lines) + "\n"
