"""TranslationNotes -> TRANSLATION_NOTES.md."""

from app_translator.ir import ImportedStack
from app_translator.ir import ServiceSpec
from app_translator.ir import TranslationNote

_HEADINGS: tuple[tuple[str, str], ...] = (
    ("needs_action", "Needs your attention"),
    ("assumed", "Assumptions made"),
    ("dropped", "Dropped"),
    ("info", "For information"),
)


def render_notes(stack: ImportedStack, service: ServiceSpec, *, source_text: str) -> str:
    lines = [
        f"# Translation notes — {service.name}",
        "",
        f"Generated by app-translator from a `{stack.source_format}` config.",
        "",
        "Everything the importer could not carry over verbatim is listed here. The app may well",
        "run without touching any of it, but these are the places where the translation is not",
        "faithful to the original.",
        "",
    ]
    for severity, heading in _HEADINGS:
        matching: list[TranslationNote] = [note for note in stack.notes if note.severity == severity]
        if not matching:
            continue
        lines += [f"## {heading}", ""]
        for note in matching:
            lines.append(f"- **`{note.field}`** — {note.message}")
        lines.append("")

    if service.secret_keys:
        lines += [
            "## Secrets this app expects",
            "",
            "The generated startup script fetches these from the compute space's secrets service on",
            "every start, in a single batched call. Set them before first launch or the app will exit",
            "with a clear error:",
            "",
        ]
        for key in service.secret_keys:
            lines.append(f"- `{key}`")
        lines.append("")

    lines += [
        "## Original config",
        "",
        f"The input is committed verbatim at `.original/{stack.source_format}` for reference.",
        "",
        "<details><summary>show</summary>",
        "",
        "```",
        source_text.strip(),
        "```",
        "",
        "</details>",
        "",
    ]
    return "\n".join(lines)
