"""ServiceSpec -> openhost-start.sh.

The shim does three things before handing control to the real process: fetch secrets
from the secrets service in a single batched call, redirect persisted paths into the
app's data directory, and exec the original command.
"""

import shlex

from app_translator.ir import ServiceSpec

# Stand-in for the app's data directory inside a command, expanded at startup so the
# generated image survives the app being renamed.
DATA_PLACEHOLDER = "@OPENHOST_DATA@"

_SECRET_FETCH = """
explain_failure() {
    status="$1"
    [ "$status" = "200" ] && return 0
    echo "openhost-start: could not read this app's secrets from the secrets service (HTTP $status)." >&2
    if [ "$status" = "403" ] || [ "$status" = "401" ]; then
        echo "openhost-start: this app asks for secrets, and that permission has not been approved yet." >&2
        echo "openhost-start: approve it at https://$OPENHOST_ZONE_DOMAIN/approve-permissions-v2 and restart the app." >&2
    elif [ "$status" = "503" ]; then
        echo "openhost-start: the secrets service is not running on this compute space." >&2
    fi
    exit 1
}

fetch_secrets() {
    keys_json=$(printf '%s' "$OPENHOST_SECRET_KEYS" | tr ' ' '\\n' | sed 's/.*/"&"/' | tr '\\n' ',' | sed 's/,$//')
    body="{\\"keys\\":[$keys_json]}"
    url="$OPENHOST_ROUTER_URL/api/services/v2/call/secrets/get"
    if command -v curl >/dev/null 2>&1; then
        http_status=$(curl -sS -o /tmp/openhost-secrets.json -w '%{http_code}' -X POST \\
            -H "Authorization: Bearer $OPENHOST_APP_TOKEN" \\
            -H "Content-Type: application/json" \\
            -d "$body" "$url") || http_status=000
        explain_failure "$http_status"
        response=$(cat /tmp/openhost-secrets.json)
    elif command -v wget >/dev/null 2>&1; then
        if ! response=$(wget -q -O - \\
            --header="Authorization: Bearer $OPENHOST_APP_TOKEN" \\
            --header="Content-Type: application/json" \\
            --post-data="$body" "$url"); then
            explain_failure 403
        fi
    elif command -v python3 >/dev/null 2>&1; then
        response=$(OPENHOST_SECRET_BODY="$body" OPENHOST_SECRET_URL="$url" python3 -c '
import json, os, urllib.request
request = urllib.request.Request(
    os.environ["OPENHOST_SECRET_URL"],
    data=os.environ["OPENHOST_SECRET_BODY"].encode(),
    headers={
        "Authorization": "Bearer " + os.environ["OPENHOST_APP_TOKEN"],
        "Content-Type": "application/json",
    },
)
print(urllib.request.urlopen(request, timeout=30).read().decode())
')
    else
        echo "openhost-start: need curl, wget or python3 in this image to fetch secrets" >&2
        exit 1
    fi

    for key in $OPENHOST_SECRET_KEYS; do
        value=$(printf '%s' "$response" | sed -n "s/.*\\"$key\\"[[:space:]]*:[[:space:]]*\\"\\([^\\"]*\\)\\".*/\\1/p")
        if [ -z "$value" ]; then
            echo "openhost-start: secret '$key' is not set on this compute space." >&2
            echo "openhost-start: set it in the secrets app, then restart this app." >&2
            exit 1
        fi
        export "$key=$value"
    done
}
"""

_EXPAND_ARGUMENTS = """
# Resolve the data-directory placeholder in the command's arguments. Done here rather
# than baked into the image so renaming the app does not break the path.
argument_count=$#
index=0
while [ $index -lt $argument_count ]; do
    argument="$1"
    shift
    case "$argument" in
        *@OPENHOST_DATA@*)
            argument=$(printf '%s' "$argument" | sed "s|@OPENHOST_DATA@|$OPENHOST_APP_DATA_DIR|g")
            ;;
    esac
    set -- "$@" "$argument"
    index=$((index + 1))
done
"""

_REDIRECT = """
redirect_path() {
    target="$1"
    store="$2"
    mkdir -p "$store"
    if [ -e "$target" ] && [ ! -L "$target" ]; then
        if [ -z "$(ls -A "$store" 2>/dev/null)" ]; then
            cp -a "$target/." "$store/" 2>/dev/null || true
        fi
        rm -rf "$target"
    fi
    mkdir -p "$(dirname "$target")"
    ln -sfn "$store" "$target"
}
"""


def render_startup_script(service: ServiceSpec, *, release_command: str | None = None) -> str:
    secret_keys = service.secret_keys
    body: list[str] = [
        "#!/bin/sh",
        "# Generated by app-translator. Runs before the app on every start.",
        "set -eu",
        "",
    ]

    if secret_keys:
        body += [
            f'OPENHOST_SECRET_KEYS="{" ".join(secret_keys)}"',
            _SECRET_FETCH.strip(),
            "",
            "fetch_secrets",
            "",
        ]

    for entry in service.data_relative_env:
        relative = (entry.value or "").lstrip("/")
        body.append(f'export {entry.key}="$OPENHOST_APP_DATA_DIR/{relative}"')
        body.append(f'mkdir -p "${entry.key}"')
    if service.data_relative_env:
        body.append("")

    symlinked = [(index, mount) for index, mount in enumerate(service.mounts) if mount.symlink_at_startup]
    if symlinked:
        body += [_REDIRECT.strip(), ""]
        for index, mount in symlinked:
            store = f'"$OPENHOST_APP_DATA_DIR"/persisted-{index}'
            body.append(f"redirect_path {shlex.quote(mount.container_path)} {store}")
        body.append("")

    for index, mount in enumerate(service.mounts):
        if not mount.symlink_at_startup:
            body.append(f'mkdir -p "$OPENHOST_APP_DATA_DIR/persisted-{index}"')
    if any(not mount.symlink_at_startup for mount in service.mounts):
        body.append("")

    if service.command and DATA_PLACEHOLDER in service.command:
        body += [_EXPAND_ARGUMENTS.strip(), ""]

    if release_command:
        body += [
            "# [deploy].release_command from the source config — runs on every start, so it must be idempotent.",
            release_command,
            "",
        ]

    body += ['exec "$@"', ""]
    return "\n".join(body)
