"""Turn a ServiceSpec into the exact set of files that make up the generated app repo."""

import attr

from app_translator.emit.dockerfile import render_dockerfile
from app_translator.emit.startup import DATA_PLACEHOLDER
from app_translator.emit.manifest import render_manifest
from app_translator.emit.notes import render_notes
from app_translator.emit.startup import render_startup_script
from app_translator.ir import ImportedStack
from app_translator.ir import ServiceSpec
from app_translator.registry import ImageConfig


class MissingCommandError(Exception):
    """The generated image needs a startup shim, but we do not know what to exec."""


@attr.s(auto_attribs=True, frozen=True)
class GeneratedFile:
    path: str
    content: str
    executable: bool = False


@attr.s(auto_attribs=True, frozen=True)
class GeneratedRepo:
    service: ServiceSpec
    files: tuple[GeneratedFile, ...]

    def file(self, path: str) -> GeneratedFile:
        for candidate in self.files:
            if candidate.path == path:
                return candidate
        raise KeyError(path)


def effective_command(service: ServiceSpec, image_config: ImageConfig | None) -> str | None:
    """The full argv to run: what the config asked for, else what the image does by default."""
    if service.command:
        return service.command
    if image_config is not None and image_config.argv:
        return " ".join(image_config.argv)
    return None


def needs_startup_shim(service: ServiceSpec, release_command: str | None) -> bool:
    return bool(
        service.secret_keys
        or service.data_relative_env
        or any(mount.symlink_at_startup for mount in service.mounts)
        or DATA_PLACEHOLDER in (service.command or "")
        or release_command
    )


def _readme(service: ServiceSpec, stack: ImportedStack) -> str:
    return "\n".join(
        [
            f"# {service.name}",
            "",
            f"{service.description or 'An app for OpenHost.'}",
            "",
            f"Generated by app-translator from a `{stack.source_format}` config.",
            "",
            "Read `TRANSLATION_NOTES.md` first — it lists everything the translation could not",
            "carry over faithfully.",
            "",
        ]
    )


def _secrets_example(service: ServiceSpec) -> str:
    lines = [
        "# Secrets this app reads at startup from the compute space's secrets service.",
        "# Fill in the values and import them into the secrets app — do not commit real values here.",
        "",
    ]
    for entry in service.env:
        if not entry.is_secret:
            continue
        if entry.description:
            lines.append(f"# {entry.description}")
        lines.append(f"{entry.key}=")
    return "\n".join(lines) + "\n"


def build_repo(
    stack: ImportedStack,
    service: ServiceSpec,
    *,
    image_config: ImageConfig | None = None,
    release_command: str | None = None,
    source_text: str = "",
) -> GeneratedRepo:
    if service.http_port is None:
        raise ValueError("a main HTTP port is required before the repo can be generated")

    command = effective_command(service, image_config)
    shim = needs_startup_shim(service, release_command)
    if shim and not command:
        raise MissingCommandError(
            "this app needs a generated startup script (for secrets or persisted paths), which has to "
            "exec the real command — but neither the source config nor the image's metadata says what "
            "that command is. Fill in the command field and try again."
        )

    service_with_command = attr.evolve(service, command=command)
    files: list[GeneratedFile] = [
        GeneratedFile("openhost.toml", render_manifest(service_with_command)),
        GeneratedFile(
            "Dockerfile",
            render_dockerfile(
                service_with_command,
                needs_startup_shim=shim,
                reset_entrypoint=bool(command),
            ),
        ),
        GeneratedFile("README.md", _readme(service_with_command, stack)),
        GeneratedFile("TRANSLATION_NOTES.md", render_notes(stack, service_with_command, source_text=source_text)),
    ]
    if shim:
        files.append(
            GeneratedFile(
                "openhost-start.sh",
                render_startup_script(service_with_command, release_command=release_command),
                executable=True,
            )
        )
    if service.secret_keys:
        files.append(GeneratedFile("secrets.example.env", _secrets_example(service_with_command)))
    if source_text:
        files.append(GeneratedFile(f".original/{stack.source_format}", source_text))

    return GeneratedRepo(service=service_with_command, files=tuple(files))
