import pytest

from app_translator.build import MissingCommandError
from app_translator.build import build_repo
from app_translator.frontends.fly_toml import parse_fly_toml
from app_translator.registry import ImageConfig

WITH_SECRET_AND_MOUNT = """
app = "grafana"

[build]
  image = "grafana/grafana:11.1.0"

[env]
  GF_USERS_ALLOW_SIGN_UP = "false"
  GF_SECURITY_ADMIN_PASSWORD = "change-me"

[http_service]
  internal_port = 3000

  [[http_service.checks]]
    path = "/api/health"

[[mounts]]
  source = "grafana_data"
  destination = "/var/lib/grafana"

[[vm]]
  memory = "512mb"
"""


def _repo(image_config: ImageConfig | None = ImageConfig(entrypoint=("/run.sh",))) -> object:
    stack = parse_fly_toml(WITH_SECRET_AND_MOUNT)
    return build_repo(stack, stack.service, image_config=image_config, source_text=WITH_SECRET_AND_MOUNT)


def test_manifest_has_the_expected_shape() -> None:
    manifest = _repo().file("openhost.toml").content
    assert 'name = "grafana"' in manifest
    assert 'image = "Dockerfile"' in manifest
    assert "port = 3000" in manifest
    assert 'health_check = "/api/health"' in manifest
    assert "memory_mb = 512" in manifest
    # The secret becomes a grant on the secrets service, not an env var.
    assert 'shortname = "secrets"' in manifest
    assert '{key = "GF_SECURITY_ADMIN_PASSWORD"}' in manifest


def test_dockerfile_bakes_plain_env_but_not_secrets() -> None:
    dockerfile = _repo().file("Dockerfile").content
    assert dockerfile.startswith("# Generated by app-translator.\nFROM grafana/grafana:11.1.0")
    assert 'ENV GF_USERS_ALLOW_SIGN_UP="false"' in dockerfile
    assert "GF_SECURITY_ADMIN_PASSWORD" not in dockerfile
    assert "ENV PORT=3000" in dockerfile
    # The shim takes over the entrypoint, so the image's own argv must come back as CMD.
    assert 'ENTRYPOINT ["/bin/sh", "/usr/local/bin/openhost-start.sh"]' in dockerfile
    # The shim is copied in as root so a non-root base image cannot break the build.
    assert dockerfile.index("USER root") < dockerfile.index("COPY openhost-start.sh")
    assert 'CMD ["/run.sh"]' in dockerfile


def test_startup_script_fetches_secrets_in_one_call_and_redirects_the_mount() -> None:
    script = _repo().file("openhost-start.sh").content
    assert script.startswith("#!/bin/sh")
    assert 'OPENHOST_SECRET_KEYS="GF_SECURITY_ADMIN_PASSWORD"' in script
    assert script.count("/api/services/v2/call/secrets/get") == 1
    assert "redirect_path /var/lib/grafana" in script
    assert script.rstrip().endswith('exec "$@"')


def test_notes_and_secrets_example_are_written() -> None:
    repo = _repo()
    notes = repo.file("TRANSLATION_NOTES.md").content
    assert "Needs your attention" in notes
    assert "GF_SECURITY_ADMIN_PASSWORD" in repo.file("secrets.example.env").content
    assert repo.file(".original/fly.toml").content.strip().startswith("app = \"grafana\"")


def test_refuses_to_generate_a_shim_with_no_command() -> None:
    with pytest.raises(MissingCommandError, match="command"):
        _repo(image_config=None)
