"""The bundled examples must stay importable — they are the first thing anyone clicks."""

from pathlib import Path

import pytest

from app_translator.build import build_repo
from app_translator.frontends.fly_toml import parse_fly_toml
from app_translator.plan import plan_persistence
from app_translator.registry import ImageConfig
from app_translator.web.app import EXAMPLES_DIR

EXAMPLES = sorted(EXAMPLES_DIR.glob("*.toml"))


def test_examples_are_shipped_with_the_package() -> None:
    assert EXAMPLES_DIR.is_dir()
    assert [path.name for path in EXAMPLES] == ["grafana.toml", "prometheus.toml"]


@pytest.mark.parametrize("path", EXAMPLES, ids=lambda path: path.name)
def test_example_translates_and_generates(path: Path) -> None:
    source = path.read_text()
    stack = parse_fly_toml(source)
    # Stand in for the registry lookup so the test needs no network.
    image = ImageConfig(entrypoint=("/entry",), exposed_ports=(stack.service.http_port or 80,), user="65534")
    service, _ = plan_persistence(stack.service, image)
    repo = build_repo(stack, service, image_config=image, source_text=source)

    manifest = repo.file("openhost.toml").content
    assert f'name = "{service.name}"' in manifest
    assert f"port = {service.http_port}" in manifest
    assert repo.file("Dockerfile").content.startswith("# Generated by app-translator.")
    assert "TRANSLATION_NOTES.md" in [generated.path for generated in repo.files]
